name: dateable
description: A Dart package to help you with managing dates easily. Can be used to store, format, convert, construct, parse and serialise dates.
version: 3.0.0+3
repository: https://github.com/SugaR256/dateable
homepage: https://github.com/SugaR256/dateable

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: '>=1.16.2 <2.0.0'
  test_coverage: ^0.5.0
