name: dateable
description: A Dart package to help you with managing dates easily. Can be used to store, format, convert, construct, parse and serialise dates.
version: 4.0.0
repository: https://github.com/SugaR256/dateable
homepage: https://github.com/SugaR256/dateable

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: '>=1.16.2 <2.0.0'