name: dateable
description: A Dart package to help you with managing dates easily. Can be used to store, convert, construct, parse and serialise dates.
version: 1.0.0+4
repository: https://github.com/SugaR256/dateable
homepage: https://github.com/SugaR256/dateable

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
