name: dateable
description: A Dart package to help you with managing dates easily. Can be used to store, format, convert, construct, parse and serialise dates.
version: 2.1.0
repository: https://github.com/SugaR256/dateable
homepage: https://github.com/SugaR256/dateable

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.2.1

dev_dependencies:
  pedantic: ^1.9.1
  test: ^1.15.2
  test_coverage: ^0.4.3
