name: coverage check
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
    - name: Install dependencies
      run: dart pub global activate coverage
    - name: Generate coverage report
      run: dart pub global run coverage:test_with_coverage --package=dateable
    - name: Submit to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
